# This is a basic workflow to help you get started with Actions

name: On-Dev-Pr-Wrokflow

# Controls when the workflow will run
on:
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow to run both backend and front end builds of the repositoy
jobs:

  # Front end build with Next/React
  FronteEndBuild:
    name: Front End Next/React Build and Test
    env:
      sourceFrontendProject: ./src/next-react-frontend
    runs-on: ubuntu-latest
    # Steps for frontend build
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: checking our code on Branch
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # npm install
      - name: Installing npm packages
        working-directory: ${{env.sourceFrontendProject}}
        run: npm install
      # npm install
      - name: Running Build
        working-directory: ${{env.sourceFrontendProject}}
        run: npm run build
      # npm test
      - name: Running Unit tests
        working-directory: ${{env.sourceFrontendProject}}
        run: npm run test

